### ISSUE TITLE
Enhancement: Mobile Chart/Character/Stage Editor Support

### ISSUE THREAD

**Issue by megalives717** [MobilePorting/CodenameEngine-Mobile#31] opened 2024-12-19 16:38 UTC

**Comment by mcagabe19** [comment] 2024-12-19 18:54
duplicate of #27

**Closed by mcagabe19** 2024-12-19 18:54 UTC
Labels: enhancement

**Comment by megalives717** [comment] 2024-12-19 18:58
PLEASE REOPEN TO MAKE MOBILE EDITOR SUPPORT!!!

**Comment by moxie-coder** [comment] 2024-12-20 09:02
> PLEASE REOPEN TO MAKE MOBILE EDITOR SUPPORT!!!

please learn what a duplicate is and stop being fucking annoying
